### PR TITLE
Add sending messages

### PR DESCRIPTION
**Pull request by Tobi406**
Add sending messages to a player.

### CODE REVIEW

**Comment by Tobi406** [comment]
As a more general question. Should there be a method in the Player class to send them a message?

**Comment by Tobi406** [comment]
And I'm also wondering if this works with multiple players. Probably doesn't.

**Comment by HurricanKai** [comment]
It does work with multiple players, if you mean echoing each back what they wrote to each player, but not to others.

I don't think there should be a Function for sending a Player a message, rather there should be a `ChatManager : IChatManager` eventually, which can be used to send messages to one or more players.
That's cleaner imo, and it will be easier to implement https://wiki.vg/Chat#Processing_chat later

**Comment by HurricanKai** [comment]
`Chat` will also eventually be extended to allow translation components and such
Which I actually had an (empty) branch locally, cause for testing it's quite important to have the chat available.

**Comment by HurricanKai** [comment]
Which I actually had an (empty) branch locally, cause for testing it's quite important to have the chat available.

**Comment by HurricanKai** [comment]
Didn't mean too, sorry

Edit: Aaaaand I killed restyled, great

**Comment by HurricanKai** [comment]
@Tobi406 What about this is WIP? Looking to merge this.

**Pull request merged**
